apiVersion: v1
kind: Service
metadata:
  name: client-web-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: client-web
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80